[project]
authors = ["Tadej Svetina <tadej.svetina@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "cpp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
clang-tools = ">=19.1.5,<20"
ninja = ">=1.12.1,<2"
cmake = ">=3.31.1,<4"
clangxx = ">=19.1.5,<20"
lld = ">=19.1.5,<20"
lldb = ">=19.1.4,<20"
llvm-tools = ">=19.1.5,<20"
include-what-you-use = ">=0.23,<0.24"
libunwind = ">=1.7.2,<2"
libcxx = ">=19.1.5,<20"
libcxx-devel = ">=19.1.5,<20"
