[project]
authors = ["Tadej Svetina <tadej.svetina@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
ruff = ">=0.8.1,<0.9"
